#pragma once

#include "config_common.h"

/* USB CONFIG */
#define USB_POLLING_INTERVAL_MS 1
#define FORCE_NKRO
/* Device descriptor parameters */
#define VENDOR_ID 0x4B4B   // KK
#define PRODUCT_ID 0x5941  // YA
#define DEVICE_VER 0x0003
#define MANUFACTURER KARLK90

// clang-format off
#define PRODUCT QMK LONGAN NANO TEMPLATE
#define DESCRIPTION LONGAN NANO
// clang-format on

/* MATRIX CONFIG */
#define MATRIX_ROWS 7
#define MATRIX_COLS 6
#define MATRIX_COL_PINS \
    { B11, B10, B1, B0, A7, A5 }
#define MATRIX_ROW_PINS \
    { B12, B13, B14, B6, B5, B4, B15 }
#define DIODE_DIRECTION COL2ROW

#define DEBUG_MATRIX_SCAN_RATE
#define DEBOUNCE 5
#define BUSY_WAIT
#define BUSY_WAIT_INSTRUCTIONS 500
#define GPIO_INPUT_PIN_DELAY 8

#define QMK_KEYS_PER_SCAN 8

/* ROTARY ENCODER*/
#define ENCODERS_PAD_A { B7 }
#define ENCODERS_PAD_B { B8 }
#define ENCODER_RESOLUTION 4

/* WS2812 DRIVER */
#define GD32_DMA_REQUIRED
#define RGBLED_NUM 8
#define DRIVER_LED_TOTAL RGBLED_NUM
#define FASTLED_SCALE8_FIXED 1
#define RGBLIGHT_LIMIT_VAL 50
#define RGBLIGHT_ANIMATIONS

/* Option 1 */
#define RGB_DI_PIN A0
#define WS2812_PWM_DRIVER PWMD2
#define WS2812_PWM_CHANNEL 1
#define WS2812_DMA_CHANNEL 2
#define WS2812_DMA_STREAM GD32_DMA0_STREAM1

/* Option 2 */
// Change GD32_PWM_USE_TIM0 to TRUE and GD32_PWM_USE_TIM1 to FALSE
// in mcuconf.h if you want this configuration.
// #define WS2812_PWM_DRIVER PWMD1
// #define WS2812_PWM_CHANNEL 3
// #define WS2812_PWM_PAL_MODE 6
// #define WS2812_DMA_CHANNEL 5
// #define WS2812_DMA_STREAM GD32_DMA0_STREAM4
// #define RGB_DI_PIN A10


/* TAPPING CONFIG */
#define TAPPING_TERM 500
#define TAPPING_TOGGLE 2
#define TAPPING_FORCE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD_PER_KEY

/* MOUSEKEY CONFIG */
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 64

/* JOYSTICK CONFIG */
#define JOYSTICK_AXES_COUNT 0
#define JOYSTICK_BUTTON_COUNT 0
